title: Another Software Craftsman's Blog
description: Spikes and PoCs I would like to share to myself
google_analytics: UA-96136221-1
show_downloads: false
theme: jekyll-theme-modernist

gems:
  - jekyll-mentions
